Importing the Dependencies

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:
# Reading The Dataset By Using Pandas 
credit_card_ds = pd.read_csv('creditcard.csv')

In [3]:
#dataset informations
credit_card_ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [4]:
#Before using dataset we need to check if there any missing value this called preprocessing 
credit_card_ds.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [5]:
# We Watch that V1 Include 24 Missing value ,We need to get rid of missing value by Calculate Mean or drop Row 
credit_card_pre_null=credit_card_ds.fillna(value=credit_card_ds['V1'].mean())
credit_card_pre_null

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [6]:
#Check again if dataset include missing value or not 
credit_card_ds.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

Congratulations for you no missing Value ♥

In [7]:
#we need in dataset number of 0 and 1, you should know that 0 represent  no fraud and 1 represent fraud
credit_card_ds['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [8]:
# separating the dataset for analysis {legal,illegal}
legal = credit_card_ds[credit_card_ds.Class == 0]
illegal = credit_card_ds[credit_card_ds.Class == 1]

In [9]:
#Build a sample dataset containing similar distribution of normal transactions and Fraudulent Transactions
legal_sample = legal.sample(n=492)

You create a new dataset consisting of an equal number of zeros and ones, or the type of operation is legal and illegal

In [10]:
new_dataset = pd.concat([legal_sample, illegal], axis=0)

In [11]:
# First 5 Rows of the dataset
new_dataset.head(100)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
98725,66782.0,1.152429,0.007362,1.293708,1.336665,-0.929870,-0.183590,-0.521875,0.059857,0.808044,...,-0.056015,0.070717,-0.012034,0.405650,0.434172,-0.410842,0.075967,0.039584,9.99,0
225497,144272.0,2.141616,-0.932543,-1.163952,-0.900739,-0.571296,-0.566921,-0.609407,-0.170433,-0.172896,...,0.201663,0.537559,0.149420,0.626493,-0.051967,-0.188411,-0.025495,-0.045948,44.65,0
281954,170558.0,2.037294,-0.473087,-0.713953,0.248657,-0.247168,0.215596,-0.706570,0.108878,1.587379,...,0.132942,0.581017,0.068701,0.041690,0.004024,-0.201199,0.032372,-0.037916,9.99,0
10989,18921.0,0.898614,0.033896,-0.083297,1.256326,0.554091,0.702342,0.155668,0.196360,1.160759,...,0.031511,0.278743,-0.027337,-0.708803,0.393032,-0.231545,0.011633,0.005579,89.99,0
60982,49592.0,1.235588,-1.324516,0.833109,-0.761773,-1.135472,1.466318,-1.450777,0.510716,0.494191,...,-0.700563,-1.173496,0.003325,-1.087419,0.069292,1.407464,-0.013470,-0.008137,40.42,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155946,106859.0,0.365880,1.779105,0.788390,4.604211,0.931659,0.178953,0.786202,-0.297053,-1.093590,...,0.262224,1.188862,-0.083193,-0.013608,-1.057369,0.373730,0.264624,0.257347,2.07,0
113829,73221.0,-1.681621,1.509069,0.183504,-1.499911,0.110332,-0.618682,0.490223,-0.933968,0.704032,...,0.822449,-0.057097,0.029922,0.042946,-0.412804,0.791119,-0.167815,0.391317,3.50,0
208671,137221.0,1.931748,-0.206247,-1.091201,0.221032,0.048929,-0.636571,0.110944,-0.203228,0.647709,...,-0.401156,-1.298485,0.452651,0.499316,-0.475824,-0.910668,-0.012974,-0.018769,68.87,0
182964,125604.0,-0.413106,1.489101,2.529333,4.181717,0.540675,1.328985,0.382438,-0.046342,-1.905583,...,0.178000,0.724595,-0.405177,0.775166,0.168086,0.491641,-0.158566,-0.126749,17.08,0
207436,136674.0,1.654891,-0.900384,-1.485874,-0.043635,0.468618,1.095820,-0.171505,0.322035,0.921867,...,0.001601,0.011429,0.095461,-1.622286,-0.289771,0.010455,-0.007737,-0.060568,140.00,0

In [12]:
# Last 5 Rows of the dataset
new_dataset.tail(100)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
204503,135314.0,-3.158990,1.765452,-3.390168,0.987410,-1.509930,-1.280952,-2.719557,0.718325,-1.660183,...,1.120533,1.605085,-0.618637,-0.251283,-0.240528,-0.004327,-0.235477,0.018129,84.28,1
208651,137211.0,0.630579,1.183631,-5.066283,2.179903,-0.703376,-0.103614,-3.490350,1.094734,-0.717418,...,0.621622,0.043807,0.102711,-0.601505,0.127371,-0.163009,0.853792,0.356503,39.45,1
212516,138894.0,-1.298443,1.948100,-4.509947,1.305805,-0.019486,-0.509238,-2.643398,1.283545,-2.515356,...,1.178032,1.360989,-0.272013,-0.325948,0.290703,0.841295,0.643094,0.201156,0.01,1
212644,138942.0,-2.356348,1.746360,-6.374624,1.772205,-3.439294,1.457811,-0.362577,1.443791,-1.927359,...,0.857942,0.621203,0.964817,-0.619437,-1.732613,0.108361,1.130828,0.415703,727.91,1
213092,139107.0,-4.666500,-3.952320,0.206094,5.153525,5.229469,0.939040,-0.635033,-0.704506,-0.234786,...,-0.664263,1.821422,0.113563,-0.759673,-0.502304,0.630639,-0.513880,0.729526,22.47,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [13]:
#Check Number of legal and illegal
new_dataset['Class'].value_counts()

0    492
1    492
Name: Class, dtype: int64

Put the data into Features & Targets

In [14]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [15]:
print(X)
print('-------------------------------------------------------------------------------------------')
print(Y)

            Time        V1        V2        V3        V4        V5        V6  \
98725    66782.0  1.152429  0.007362  1.293708  1.336665 -0.929870 -0.183590
225497  144272.0  2.141616 -0.932543 -1.163952 -0.900739 -0.571296 -0.566921
281954  170558.0  2.037294 -0.473087 -0.713953  0.248657 -0.247168  0.215596
10989    18921.0  0.898614  0.033896 -0.083297  1.256326  0.554091  0.702342
60982    49592.0  1.235588 -1.324516  0.833109 -0.761773 -1.135472  1.466318
...          ...       ...       ...       ...       ...       ...       ...
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7        V8        V9  ...       V20       V21       V22  \
98725  -0.521875  0.059857  0.808044  ... -0.097098 -0.056015  0.070717
225497 -0.609407 -0.170433 -0.172896  ...  0.039622  0.201663  0.537559
281954 -0.706570  0.108878  1.587379  ... -0.200316  0.132942  0.581017
10989   0.155668  0.196360  1.160759  ... -0.252497  0.031511  0.278743
60982  -1.450777  0.510716  0.494191  ... -0.431124 -0.700563 -1.173496
...          ...       ...       ...  ...       ...       ...       ...
279863 -0.882850  0.697211 -2.064945  ...  1.252967  0.778584 -0.319189
280143 -1.413170  0.248525 -1.127396  ...  0.226138  0.370612  0.028234
280149 -2.234739  1.210158 -0.652250  ...  0.247968  0.751826  0.834108
281144 -2.208002  1.058733 -1.632333  ...  0.306271  0.583276 -0.269209
281674  0.223050 -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135

             V23       V24       V25       V26       V27       V28  Amount
98725  -0.012034  0.405650  0.434172 -0.410842  0.075967  0.039584    9.99
225497  0.149420  0.626493 -0.051967 -0.188411 -0.025495 -0.045948   44.65
281954  0.068701  0.041690  0.004024 -0.201199  0.032372 -0.037916    9.99
10989  -0.027337 -0.708803  0.393032 -0.231545  0.011633  0.005579   89.99
60982   0.003325 -1.087419  0.069292  1.407464 -0.013470 -0.008137   40.42
...          ...       ...       ...       ...       ...       ...     ...
279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00
280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76
280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89
281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00
281674 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53

[984 rows x 30 columns]
-------------------------------------------------------------------------------------------
98725     0
225497    0
281954    0
10989     0
60982     0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

In [16]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X_train= sc.fit_transform(X )
pd.DataFrame(X_train)

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,-0.423500,0.641614,-0.491659,0.772319,-0.290777,0.160434,0.307428,0.388673,-0.040939,0.878137,...,-0.248046,-0.151949,0.062706,0.018294,0.775305,0.612197,-0.894309,-0.009512,0.010527,-0.378302
1,1.205984,0.820664,-0.746373,0.376993,-0.987034,0.246324,0.085088,0.373688,-0.087974,0.462010,...,-0.125016,-0.061153,0.456776,0.156670,1.172053,-0.114796,-0.433784,-0.108770,-0.158835,-0.241361
2,1.758734,0.801781,-0.621860,0.449377,-0.629354,0.323963,0.538964,0.357053,-0.030927,1.208740,...,-0.340929,-0.085367,0.493460,0.087489,0.121447,-0.031065,-0.460260,-0.052159,-0.142931,-0.378302
3,-1.429937,0.595671,-0.484468,0.550821,-0.315778,0.515890,0.821287,0.504668,-0.013060,1.027763,...,-0.387885,-0.121108,0.238305,0.005179,-1.226825,0.550674,-0.523088,-0.072448,-0.056806,-0.062224
4,-0.784977,0.656666,-0.852597,0.698230,-0.943789,0.111186,1.264409,0.229646,0.051145,0.744997,...,-0.548625,-0.379061,-0.987557,0.031458,-1.907013,0.066541,2.870348,-0.097006,-0.083966,-0.258074
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
979,1.728958,0.084055,-0.188602,-0.162576,-0.162372,0.007944,-0.752214,0.326874,0.089235,-0.340620,...,0.966832,0.142131,-0.266420,0.576626,-0.483215,0.766722,1.588615,0.202495,0.225136,1.123111
980,1.733269,0.682545,-0.144232,-0.240738,-0.267381,0.489179,-0.355504,0.236084,-0.002405,0.057100,...,0.042823,-0.001622,0.026846,-0.096213,-0.099056,0.743352,1.487314,0.296871,0.301703,-0.414770
981,1.733353,0.310629,-0.188409,0.208136,-0.561001,0.114762,0.411973,0.095432,0.194000,0.258662,...,0.062467,0.132702,0.707099,0.192258,0.104164,-1.143254,0.931704,0.292915,0.316999,-0.110031
982,1.746285,-0.130611,-0.334885,-0.304353,-0.141273,0.181813,-1.293405,0.100009,0.163073,-0.157101,...,0.114932,0.073312,-0.224231,-0.362301,-0.283396,-0.527839,1.211220,0.781829,-0.570201,0.550218
983,1.754318,0.793578,-0.450707,0.148661,-0.579560,0.658903,0.357829,0.516204,-0.067131,0.780477,...,-0.176556,-0.190121,-0.246116,-0.033247,-0.762350,0.431390,-0.643321,-0.080906,-0.098166,-0.249737

In [17]:
#Seperate dataset to some train and some test 
X_train, X_test, Y_train, Y_test = train_test_split(X_train, Y, test_size=0.20, stratify=Y, random_state=2)

In [18]:
#show how many row train and how many row for test
print(X.shape, X_train.shape, X_test.shape)

(984, 30) (787, 30) (197, 30)

In [19]:
from sklearn.naive_bayes import GaussianNB # import library naive_bayes 
from sklearn.linear_model import LogisticRegression #import library NaiveBayes 
from sklearn.neighbors import KNeighborsClassifier #import library K Nearest Neighbors
from sklearn.svm import SVC #import library Support Vector machine 
from sklearn.ensemble import RandomForestClassifier

# using Model Training Logistic Regression
model1 = LogisticRegression()
model2 = GaussianNB()
model3 = SVC(kernel='linear', random_state = 0, C=10)
model4 = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
model5 =  RandomForestClassifier(n_estimators = 10 , criterion = 'entropy', random_state = 10)

#Traing Models
model1.fit(X_train, Y_train)#training the Logistic Regression Model with Training Data
model2.fit(X_train, Y_train)#training the NaiveBayes  Model with Training Data
model3.fit(X_train, Y_train)#training the K Nearest Neighbors Model with Training Data
model4.fit(X_train, Y_train)#training the Support Vector machine  Model with Training Data
model5.fit(X_train, Y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=10)

In [20]:
#calculcate Accuracy on Training data
X_train_prediction1 = model1.predict(X_train)
training_data_accuracy1 = accuracy_score(X_train_prediction1, Y_train)

X_train_prediction2 = model2.predict(X_train)
training_data_accuracy2 = accuracy_score(X_train_prediction2, Y_train)

X_train_prediction3 = model3.predict(X_train)
training_data_accuracy3 = accuracy_score(X_train_prediction3, Y_train)

X_train_prediction4 = model4.predict(X_train)
training_data_accuracy4 = accuracy_score(X_train_prediction4, Y_train)

X_train_prediction5 = model5.predict(X_train)
training_data_accuracy5 = accuracy_score(X_train_prediction5, Y_train)

print('Accuracy on Training data_LogisticRegression : ', training_data_accuracy1)
print('Accuracy on Training data_NaiveBayes : ', training_data_accuracy2)
print('Accuracy on Training data_SVC : ', training_data_accuracy3)
print('Accuracy on Training data_Knn : ', training_data_accuracy4)
print('Accuracy on Training data_RandomForest : ', training_data_accuracy5)

Accuracy on Training data_LogisticRegression :  0.951715374841169
Accuracy on Training data_NaiveBayes :  0.9085133418043202
Accuracy on Training data_SVC :  0.9567979669631512
Accuracy on Training data_Knn :  0.9415501905972046
Accuracy on Training data_RandomForest :  0.9961880559085133

In [21]:
#calculcate Accuracy score on Test Data
X_test_prediction1 = model1.predict(X_test)
test_data_accuracy1 = accuracy_score(X_test_prediction1, Y_test)

X_test_prediction2 = model2.predict(X_test)
test_data_accuracy2 = accuracy_score(X_test_prediction2, Y_test)

X_test_prediction3 = model3.predict(X_test)
test_data_accuracy3 = accuracy_score(X_test_prediction3, Y_test)

X_test_prediction4 = model4.predict(X_test)
test_data_accuracy4 = accuracy_score(X_test_prediction4, Y_test)

X_test_prediction5 = model5.predict(X_test)
test_data_accuracy5 = accuracy_score(X_test_prediction5, Y_test)

print('Accuracy score on Test Data LogisticRegression: ', test_data_accuracy1)
print('Accuracy score on Test Data NaiveBayes : ', test_data_accuracy2)
print('Accuracy score on Test Data SVC : ', test_data_accuracy3)
print('Accuracy score on Test Data  Knn : ', test_data_accuracy4)
print('Accuracy score on Test Data RandomForest : ', test_data_accuracy5)

Accuracy score on Test Data LogisticRegression:  0.9441624365482234
Accuracy score on Test Data NaiveBayes :  0.9086294416243654
Accuracy score on Test Data SVC :  0.949238578680203
Accuracy score on Test Data  Knn :  0.9137055837563451
Accuracy score on Test Data RandomForest :  0.9238578680203046

In [22]:
from sklearn.metrics import confusion_matrix
cm1 = confusion_matrix(Y_test, X_test_prediction1)
print('confusion_matrix LogisticRegression :')
pd.DataFrame(cm1)

confusion_matrix LogisticRegression :

    0   1
0  98   1
1  10  88

In [23]:
cm2 = confusion_matrix(Y_test, X_test_prediction2)
print('confusion_matrix NaiveBayes : ')
pd.DataFrame(cm2)

confusion_matrix NaiveBayes :

    0   1
0  97   2
1  16  82

In [24]:
cm3 = confusion_matrix(Y_test, X_test_prediction3)
print('confusion_matrix SVC : ')
pd.DataFrame(cm3)

confusion_matrix SVC :

    0   1
0  98   1
1   9  89

In [25]:
cm4 = confusion_matrix(Y_test, X_test_prediction4)
print('confusion_matrix data_Knn :')
pd.DataFrame(cm4)

confusion_matrix data_Knn :

    0   1
0  96   3
1  14  84

In [26]:
cm5 = confusion_matrix(Y_test, X_test_prediction5)
print('confusion_matrix RandomForest : ')
pd.DataFrame(cm5)

confusion_matrix RandomForest :

    0   1
0  99   0
1  15  83